# Diabetes Prediction Using Ensemble Learning

In [1]:
import numpy as np
import pandas as pd
import pandas_profiling

In [91]:
diabetes_data = pd.read_csv(r'C:\Users\Lenovo\Desktop\Python_exercise\DS_diabetes-prediction\diabetes.csv')

In [81]:
diabetes_data.head()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   
2            8      183             64              0        0  23.3   
3            1       89             66             23       94  28.1   
4            0      137             40             35      168  43.1   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.627   50        1  
1                     0.351   31        0  
2                     0.672   32        1  
3                     0.167   21        0  
4                     2.288   33        1

In [82]:
# diabetes_data.profile_report(style={'full_width':True})

In [83]:
def Insulin():
    return int(np.random.normal(100,20, size = 1 ))

In [15]:
int(np.random.normal(100, 20, size=1))

85

In [84]:
def BloodPressure():
    return int(np.random.normal(75,20, size = 1 ))

In [85]:
def BMI():
    return int(np.random.normal(30, 5, size=1))

In [86]:
def SkinThickness():
    return int(np.random.normal(20,10, size = 1))

In [92]:
diabetes_data["Insulin"] = diabetes_data["Insulin"].replace(0, Insulin())
diabetes_data['BloodPressure'] = diabetes_data["BloodPressure"].replace(0, BloodPressure())
diabetes_data['BMI'] = diabetes_data["BMI"].replace(0, BMI())
diabetes_data["SkinThickness"] = diabetes_data["SkinThickness"].replace(0, SkinThickness())



In [55]:
# diabetes_data.profile_report(style={'full_width':True})

In [18]:
np.random.normal(100,20)

114.59058704582492

In [42]:
diabetes_data['SkinThickness'].std()

15.952217567727677

In [40]:
diabetes_data.columns

Index(['Pregnancies', 'Glucose', 'BloodPressure', 'SkinThickness', 'Insulin',
       'BMI', 'DiabetesPedigreeFunction', 'Age', 'Outcome'],
      dtype='object')

In [93]:
diabetes_data.head()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35      105  33.6   
1            1       85             66             29      105  26.6   
2            8      183             64             26      105  23.3   
3            1       89             66             23       94  28.1   
4            0      137             40             35      168  43.1   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.627   50        1  
1                     0.351   31        0  
2                     0.672   32        1  
3                     0.167   21        0  
4                     2.288   33        1

In [97]:
X = diabetes_data.drop('Outcome', axis=1)

In [98]:
y = diabetes_data['Outcome']

In [99]:
y.head()

0    1
1    0
2    1
3    0
4    1
Name: Outcome, dtype: int64

In [100]:
from sklearn.preprocessing import StandardScaler

In [111]:
from sklearn.model_selection import train_test_split

In [101]:
scaler = StandardScaler()

In [102]:
scaled_X = scaler.fit_transform(X)

In [128]:
X_train,X_test, y_train, y_test = train_test_split(scaled_X,y,test_size = 0.2)

In [107]:
from sklearn import neighbors

In [109]:
knn = neighbors.KNeighborsClassifier(n_neighbors=5)

In [129]:
y_train.shape

(614,)

In [130]:
model = knn.fit(X_train, y_train)

In [135]:
knn.predict([
    [1,3,4,56,7,8,100,3]
#     [1,3,4,56,7,8,9,3]
    
])

array([1], dtype=int64)

In [137]:
knn.score(X_test, y_test)

0.7077922077922078

In [147]:
y_pred = knn.predict(X_test)

In [148]:
print(y_pred)

[1 1 0 0 0 0 0 1 0 1 1 0 1 1 0 0 1 0 1 1 1 0 1 0 0 0 0 0 0 1 0 0 0 0 0 1 0
 1 1 0 0 1 0 0 1 0 0 0 0 0 1 0 0 1 1 1 0 1 0 1 0 0 1 1 0 0 1 0 1 0 0 0 0 0
 1 1 0 0 1 0 0 0 0 0 0 1 0 0 1 1 1 1 1 0 1 0 0 0 1 1 0 1 1 0 0 0 1 1 0 1 1
 1 0 1 1 0 0 0 0 0 0 0 0 0 0 1 0 1 0 0 0 0 0 1 0 0 0 1 1 0 1 0 0 0 1 0 1 1
 1 1 1 1 0 0]


In [151]:
np.array(y_test)

array([1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0,
       1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0,
       1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1,
       1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1,
       0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0,
       1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1],
      dtype=int64)

In [152]:
accuracy_score(y_test, y_pred)

0.7727272727272727

In [138]:
from sklearn.metrics import accuracy_score

In [154]:
knn.score(X_test, y_test)

0.7727272727272727

In [155]:
from sklearn.linear_model import LogisticRegression

In [156]:
from sklearn. naive_bayes import GaussianNB

In [157]:
naive_bayes = GaussianNB()
logistic = LogisticRegression()

In [185]:
NB = naive_bayes.fit(X_train, y_train)

In [159]:
naive_bayes.score(X_test, y_test)

0.7467532467532467

In [160]:
y_pred = naive_bayes.predict(X_test)

In [162]:
accuracy_score(y_pred, y_test)

0.7467532467532467

In [163]:
lr = logistic.fit(X_train,y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [164]:
logistic.score(X_test, y_test)

0.7857142857142857

In [187]:
prediction = [
    [-0.54791859, -0.02799627,  0.29125302,  0.98611275, -0.29254861,
         1.04477944, -0.77579692, -0.36084741]]
#        [ 0.63994726, -0.56004775, -0.03951566,  0.4244585 ,  0.66635746,
#          0.7542319 , -0.44660398,  1.85143417],
#        [-0.54791859, -0.96691063, -1.0318217 , -0.2495266 , -0.29254861,
#         -1.30865562, -0.84827977, -0.70119842],
#        [-0.84488505, -0.05929342, -1.52797472, -1.70982765, -0.91301724,
#         -1.48298415, -0.8059981 , -0.78628618],
#        [-0.54791859,  2.38188392, -0.2049    ,  1.88475955,  4.64863794,
#         -0.29173924, -0.94794368,  1.68125866]]
    

In [188]:
model.predict(prediction)

array([0], dtype=int64)

In [189]:
pred_algorithm = [model, NB, logistic]


In [213]:
from sklearn.ensemble import VotingClassifier
model1 = LogisticRegression(random_state=1)
model2 = GaussianNB()
# model3 = neighbors.KNeighborsClassifier(n_neighbors=5, weights = 'distance')
model = VotingClassifier(estimators=[('lr', model1), ('NB', model2)], voting='hard')
model.fit(X_train,y_train)
model.score(X_test,y_test)

0.7857142857142857